# Generated by Django 6.1.1 on 2026-09-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('HALFTIME', 'Half-time'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=16)),
                ('kickoff_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='league.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.competition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='league.team')),
            ],
            options={
                'ordering': ['-kickoff_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GOAL', 'Goal'), ('YELLOW', 'Yellow Card'), ('RED', 'Red Card'), ('SUBSTITUTION', 'Substitution'), ('HALFTIME', 'Half-time'), ('FULLTIME', 'Full-time')], max_length=16)),
                ('minute', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='league.player')),
                ('related_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to='league.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='league.team')),
            ],
            options={
                'ordering': ['minute', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['competition', 'status'], name='matches_mat_competi_a94d27_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['kickoff_at'], name='matches_mat_kickoff_e3db3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='match_home_away_teams_differ'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'type'], name='matches_mat_match_i_87d27e_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', 'minute'], name='matches_mat_match_i_3c5afa_idx'),
        ),
    ]
