# Generated by Django 6.1.1 on 2026-09-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='bench_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='matchlineup',
            index=models.Index(fields=['match', 'is_starter'], name='matches_mat_match_i_6a23d4_idx'),
        ),
    ]
