# Generated by Django 6.1.1 on 2026-09-18 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_fantasy_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_teams', to='league.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_teams', to='league.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FantasyPlayerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=False)),
                ('is_captain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_selections', to='league.player')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_selections', to='league.stage')),
                ('fantasy_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='fantasy.fantasyteam')),
            ],
        ),
        migrations.CreateModel(
            name='FantasyGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fantasy.fantasygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='uniq_user_per_fantasy_group')],
            },
        ),
        migrations.CreateModel(
            name='FantasyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_points', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_points', to='league.player')),
            ],
            options={
                'indexes': [models.Index(fields=['match'], name='fantasy_fan_match_i_6f629b_idx'), models.Index(fields=['player'], name='fantasy_fan_player__bf30bf_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='uniq_fantasy_points_per_match_player')],
            },
        ),
        migrations.AddConstraint(
            model_name='fantasyteam',
            constraint=models.UniqueConstraint(fields=('user', 'competition', 'season'), name='uniq_fantasy_team_per_user_comp_season'),
        ),
        migrations.AddIndex(
            model_name='fantasyplayerselection',
            index=models.Index(fields=['fantasy_team', 'stage', 'is_starter'], name='fantasy_fan_fantasy_d37e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasyplayerselection',
            index=models.Index(fields=['fantasy_team', 'stage', 'is_captain'], name='fantasy_fan_fantasy_0d709d_idx'),
        ),
        migrations.AddConstraint(
            model_name='fantasyplayerselection',
            constraint=models.UniqueConstraint(fields=('fantasy_team', 'stage', 'player'), name='uniq_player_per_team_stage'),
        ),
    ]
