# Generated by Django 6.1.1 on 2026-09-18 15:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
        ('league', '0002_teammanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='starting_budget',
            field=models.DecimalField(decimal_places=1, default=Decimal('100.0'), max_digits=6),
        ),
        migrations.CreateModel(
            name='FantasyPlayerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_price', to='league.player')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
