# Generated by Django 6.1.1 on 2026-09-18 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_fantasyteam_starting_budget_fantasyplayerprice'),
        ('league', '0002_teammanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fantasy_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='fantasy.fantasyteam')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fantasy_transfers_in', to='league.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fantasy_transfers_out', to='league.player')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_transfers', to='league.stage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fantasy_team', 'stage'], name='fantasy_fan_fantasy_c7dd3b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('player_out', models.F('player_in')), _negated=True), name='fantasy_transfer_out_differs_from_in')],
            },
        ),
    ]
