# Generated by Django 6.1.1 on 2026-09-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_fantasytransfer'),
        ('league', '0002_teammanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyChipUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_type', models.CharField(choices=[('WILDCARD', 'Wildcard'), ('FREE_HIT', 'Free Hit'), ('BENCH_BOOST', 'Bench Boost'), ('TRIPLE_CAPTAIN', 'Triple Captain')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='fantasyplayerselection',
            name='uniq_player_per_team_stage',
        ),
        migrations.RemoveIndex(
            model_name='fantasyplayerselection',
            name='fantasy_fan_fantasy_d37e9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='fantasyplayerselection',
            name='fantasy_fan_fantasy_0d709d_idx',
        ),
        migrations.AddField(
            model_name='fantasyplayerselection',
            name='is_free_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fantasytransfer',
            name='counts_toward_limit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fantasyplayerselection',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_selections', to='league.stage'),
        ),
        migrations.AddIndex(
            model_name='fantasyplayerselection',
            index=models.Index(fields=['fantasy_team', 'stage', 'is_free_hit', 'is_starter'], name='fantasy_fan_fantasy_bced82_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasyplayerselection',
            index=models.Index(fields=['fantasy_team', 'stage', 'is_free_hit', 'is_captain'], name='fantasy_fan_fantasy_5f7c54_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasytransfer',
            index=models.Index(fields=['fantasy_team', 'stage', 'counts_toward_limit'], name='fantasy_fan_fantasy_09cd65_idx'),
        ),
        migrations.AddConstraint(
            model_name='fantasyplayerselection',
            constraint=models.UniqueConstraint(fields=('fantasy_team', 'stage', 'player', 'is_free_hit'), name='uniq_player_per_team_stage_and_hit'),
        ),
        migrations.AddField(
            model_name='fantasychipuse',
            name='fantasy_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_uses', to='fantasy.fantasyteam'),
        ),
        migrations.AddField(
            model_name='fantasychipuse',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_uses', to='league.season'),
        ),
        migrations.AddField(
            model_name='fantasychipuse',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_uses', to='league.stage'),
        ),
        migrations.AddConstraint(
            model_name='fantasychipuse',
            constraint=models.UniqueConstraint(fields=('fantasy_team', 'season', 'chip_type'), name='uniq_chip_per_team_season'),
        ),
        migrations.AddConstraint(
            model_name='fantasychipuse',
            constraint=models.UniqueConstraint(fields=('fantasy_team', 'stage'), name='uniq_chip_per_team_stage'),
        ),
    ]
